
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: yarn dev
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
       - node_modules:/node_modules
    environment:
      - NODE_ENV=development 